# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.0"
manifest_format = "2.0"
project_hash = "1dfb581ad29f8d9cdfdb9597cdd74222e969fa89"

[[deps.IPOMDPs]]
git-tree-sha1 = "359afe7e2ea4ed3f9697729588320ea259f49136"
repo-rev = "master"
repo-url = "https://github.com/jaysulk/IPOMDPs.jl"
uuid = "400b8fa6-c29f-11e8-147f-97038bb7f9c1"
version = "0.1.0"
