name = "IPOMDPToolbox"
uuid = "2652b0b7-dbff-4704-a554-3df8ced9e591"
authors = ["Jason A. Sulskis <jason.sulskis@gmail.com>"]
version = "0.1.0"

[deps]
IPOMDPs = "400b8fa6-c29f-11e8-147f-97038bb7f9c1"
